### ISSUE TITLE
User Authentication and Integration with FlowFuse

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/node-red-dashboard#1]
## Description
I would like to propose the implementation of User Authentication and integration with FlowForge Authentication. This feature would enable the creation of user-specific applications and dashboards, as well as the ability to share dashboards among users.

## Proposed Solution

- Implement a user authentication system that supports secure login and access control for dashboard users.
- Integrate the authentication system with FlowForge Authentication to streamline user management and ensure consistency across the platform.
- Provide the ability to create user-specific applications and dashboards, which would allow users to customize their experience and access control on a per-user basis.
- Enable users to share dashboards with other authenticated users, allowing for collaboration and efficient sharing of resources.

**Comment by MarianRaphael** [comment]
EE Feature (different repo/package)

**Comment by wernermorgenstern** [comment]
I have a few suggestions/wants.  Some of these might not be relevant, since we are not using Flowforge.  We are using Node-Red 3.0.2, with the Dashboard on another service, which integrates with other instances through Websockets and API Calls.

1.  Allow OAuth2 or SAML Authentication with a third-party (e.g. Gitlab).  We use Gitlab Signin now for the Node-Red Editor, it would be nice to allow similar authentication into the Dashboard
2.  Allow multiple users for Dashboard.  Currently, we can only have one user defined through the settings.js file

**Comment by MarianRaphael** [comment]
Moved to https://github.com/FlowFuse/nr-dashboard-multiuser
