### ISSUE TITLE
ui-dropdown - Dropdown shows "No options available" when options are provided dynamically

### ISSUE THREAD

**Issue by adamf-datapath** [FlowFuse/node-red-dashboard#1011]
### Current Behavior

When providing options dynamically to ui-dropdown by setting `msg.options`, the rendered dropdown states there are "No options available", even though there are.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/65651105/4a730131-4f36-4906-9fba-cecf117cc1c4)

### Expected Behavior

Dropdown does not warn about no options available.

### Steps To Reproduce

1. Pass a list of options (via `msg.options`) to ui-dropdown, in response to ui-event.
2. View the dashboard. The options will be present in the dropdown, but the error will be shown.

Reproduction:

```
[
    {
        "id": "35a00fcc21bff589",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "2aa91d68bd7d2cf7",
        "type": "ui-dropdown",
        "z": "35a00fcc21bff589",
        "group": "e5ee6bb9bf33fc5f",
        "name": "",
        "label": "Select Option:",
        "tooltip": "",
        "order": 1,
        "width": 0,
        "height": 0,
        "passthru": false,
        "multiple": false,
        "options": [],
        "payload": "",
        "topic": "topic",
        "topicType": "msg",
        "className": "",
        "x": 960,
        "y": 200,
        "wires": [
            [
                "e0d608487ccd1149"
            ]
        ]
    },
    {
        "id": "e0d608487ccd1149",
        "type": "debug",
        "z": "35a00fcc21bff589",
        "name": "debug 3",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 960,
        "y": 260,
        "wires": []
    },
    {
        "id": "9cd6c91afcdbfb2f",
        "type": "change",
        "z": "35a00fcc21bff589",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "options",
                "pt": "msg",
                "to": "[{\"value\":1,\"label\":\"One\"},{\"value\":2,\"label\":\"Two\"}]",
                "tot": "json"
            },
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "test-topic",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 720,
        "y": 200,
        "wires": [
            [
                "2aa91d68bd7d2cf7",
                "e0d608487ccd1149"
            ]
        ]
    },
    {
        "id": "5456420d981161db",
        "type": "ui-event",
        "z": "35a00fcc21bff589",
        "ui": "e578ecf151797c4b",
        "name": "",
        "x": 550,
        "y": 200,
        "wires": [
            [
                "9cd6c91afcdbfb2f"
            ]
        ]
    },
    {
        "id": "489a7c8d00a851bb",
        "type": "inject",
        "z": "35a00fcc21bff589",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 570,
        "y": 120,
        "wires": [
            [
                "2aa91d68bd7d2cf7"
            ]
        ]
    },
    {
        "id": "e5ee6bb9bf33fc5f",
        "type": "ui-group",
        "name": "Test",
        "page": "6722c437d7090ba4",
        "width": "6",
        "height": "1",
        "order": 1,
        "showTitle": true,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "e578ecf151797c4b",
        "type": "ui-base",
        "name": "My Dashboard",
        "path": "/dashboard",
        "includeClientData": true,
        "acceptsClientConfig": [
            "ui-notification",
            "ui-control",
            "ui-button",
            "ui-dropdown"
        ],
        "showPathInSidebar": false,
        "navigationStyle": "fixed",
        "titleBarStyle": "default"
    },
    {
        "id": "6722c437d7090ba4",
        "type": "ui-page",
        "name": "Test",
        "ui": "e578ecf151797c4b",
        "path": "/test",
        "icon": "home",
        "layout": "grid",
        "theme": "311d097b7376955f",
        "order": 1,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "311d097b7376955f",
        "type": "ui-theme",
        "name": "Default Theme",
        "colors": {
            "surface": "#ffffff",
            "primary": "#0094ce",
            "bgPage": "#eeeeee",
            "groupBg": "#ffffff",
            "groupOutline": "#cccccc"
        },
        "sizes": {
            "pagePadding": "12px",
            "groupGap": "12px",
            "groupBorderRadius": "4px",
            "widgetGap": "12px"
        }
    }
]
```

### Environment

- Dashboard version: 1.12.0
- Node-RED version: 3.1.7
- Node.js version: 18.19.1
- npm version: 10.2.4
- Platform/OS: Windows
- Browser: Edge

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by arturv2000** [comment]
Just tested your example flow, can confirm that it happens.

One work-around is to define an empty `option` on the node config...

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/0c59cac5-9d3f-4225-ac07-02c9b2d0a674)

It seems to remove that error.

Strange never had found that error, well, by default when we add a new Dropdown node to the dashboard the node by default has one empty `option`, unless we remove it the error would not trigger.

**Comment by bartbutenaers** [comment]
Hmm not sure how to fix this, because I have never used the ui-control node myself.  
Seems to be 2 different problems.

## Problem 1: incorrect error label

The 2 options are extracted correctly from the input message, and returned by the computed `options` property:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/2da7ff53-693d-4db0-9947-05e15eeb140b)

Which should trigger the label to be hidden:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/22b83737-46d9-4d5b-ac7c-a0f584df3b75)

Although I 'think' that the first `?` is a typo?  I did remove it, but the label is still being displayed.

## Problem 2: no value selected

This is what happens:

1. The ui-control node injects this message:

   ![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/f6dcdd73-cfb9-4a58-8173-05a26880f808)

2. Which arrives in the recently added dynamic property mechanism:

   ![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/c2542885-3060-4bda-9d35-e475d0911997)

3. The options are correctly extracted from the message:

   ![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/dd02e7d0-50e2-49d3-a2d1-3c28b353db88)

4. But then the node tries to determine which of these options need to be selected, by looking at the payload:

   ![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/2d22a556-5f2d-4163-a67f-277442f84dc6)

   Since the msg.payload value is not available in the list of options, nothing will be selected.

So I assume the input message payload should be fixed by the user's flow?  Although imho it would be user friendly to show a `node.error` that the `msg.payload` contains no valid option...

**Comment by arturv2000** [comment]
Regarding the first problem, i would say the error is in this line:

https://github.com/FlowFuse/node-red-dashboard/blob/240a03ca1b55702ef444039d08a7e38623ec3c58/ui/src/widgets/ui-dropdown/UIDropdown.vue#L15

I think it should be:
```js
:error-messages="options?.length ? '' : 'No options available'"
```

since after we send a message with the `options` field, the item list is in variable `items` that is fetched by the compute propriety `options`.

Making this change (tested on vuetify playground), it seems that the warning `red color` will appear in case we send a message with `options` as an empty array, and in case the node config windows doesn't have any option. Will be refreshed after we send a message with `options` at startup.


I don't think the 2 problem, is a really "issue". Having no value selected, in the example flow that indeed happens because the `payload` is not valid considering the `options`, I would argue that the user should send a valid payload or not send any payload.

In my opinion it is valid that I may only want to update the `options` (Item List) without assigning any value. And, it would be useful to have some way to purposely clear the comboBox and return to the original state (with no item selected).

**Comment by bartbutenaers** [comment]
> I think it should be

Yes you are correct that is the one.  Build and tested it, and then it works.  Thanks!!
I have created a [pull request](https://github.com/FlowFuse/node-red-dashboard/pull/1013).

**Comment by bartbutenaers** [comment]
> In my opinion it is valid that I may only want to update the options (Item List) without assigning any value

Yes true.  But if you inject a payload with an invalid content, imho it would be userfriendly to show a warning in the sidebar.

**Comment by arturv2000** [comment]
> > In my opinion it is valid that I may only want to update the options (Item List) without assigning any value
> 
> Yes true. But if you inject a payload with an invalid content, imho it would be userfriendly to show a warning in the sidebar.

Yes agree, the same way other nodes send `error`/`warn` messages to the debug tab.

Although the action of sending only the `options` should maybe also clear the Dropdown value, specially if the selected value is not present in the new options to avoid inconsistency.. Or maybe more simple to have a way to clear the selection, like an empty string on payload.
