### ISSUE TITLE
Icons on dashboard 2

### ISSUE THREAD

**Issue by gtnscebba** [FlowFuse/node-red-dashboard#1031]
### Description

I use dashboard 2 on native NodeRed (4.0). I'm migrating from dashboard 1 to dashboard 2. 
I ask you wich icons I can choose for 'icon' on a page entry.
In dashboard 1 I could use thats of Material Design (https://klarsys.github.io/angular-material-icons/): I've tried to use them but they are non recognized.
Could you tell me what use and how to access them?
Thanks a lot.

### Properties

- Style

### Events

- **on-action**: this widget would need to send a message back to Node-RED when it's action is triggered, e.g. button clicked
- **on-change**: this widget would need to send a message back to Node-RED when it's value is changed/updated

### Controls

- **enabled**: this widget can be enabled/disabled
- **visible**: this widget can be hidden

### Existing Examples

We use Vuetify for a lot of our widgets, is there a Vuetify component that is similar to what you are looking for?

### Have you provided an initial effort estimate for this issue?

I have not provided an initial effort estimate
```[tasklist]
### Tasks
```

**Comment by arturv2000** [comment]
The icons names are available in this site:
https://pictogrammers.com/library/mdi/

In order to use them in the widget configuration, for example `button` just copy the icon name:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/1698a338-d4b3-4451-81dd-a292fd0acaeb)

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/a5a504df-e60c-4739-8c59-5f44a63b1389)

Some other widgets support adding icons on the configuration.

In a template, it is possible to use as such (it is necessary to add `mdi-` to the icon name), there are probably other ways to use it...

```
<v-icon icon="mdi-power"></v-icon>
```

**Comment by gtnscebba** [comment]
Thanks a loto for your answer, very very quick.

**Comment by gtnscebba** [comment]
Fantastic support
