### ISSUE TITLE
Try import Univer (Spreadsheet)

### ISSUE THREAD

**Issue by buschhardtt** [FlowFuse/node-red-dashboard#1100]
Hallo, I try to show a spreadsheet app [Univer js](https://univer.ai/guides/sheet/getting-started/installation) on my dashboard

Here are my steps
1. install with npm univer packages into `/home/username/.node-red/node_modules` like on univer-page
2. add a dashboard 2.0 template-node on the board
3. copy the sourcecode from https://github.com/awesome-univer/sheets-vue3-demo/blob/main/src/components/UniverSheet.vue into template

I dont see any spreadsheet or error messages in debugview. I try also to change the import-path to "../@univerjsxxx", but with no luck.
Can You help me? My Vue-knowledge is very little.

Thank You Thomas

**Comment by joepavitt** [comment]
Unfortunately, we don't support `import` statements in the `ui-template`. In order to import third-party nodes, you need to load them via `<script>` tags - see [docs](https://dashboard.flowfuse.com/nodes/widgets/ui-template.html#loading-external-dependencies).

You can point this to local files on your Node-RED server, but your server needs to be configured to expose these to the Dashboard. I haven't got an example of this into the docs yet, but you can see it in the Node-RED Forums here: https://discourse.nodered.org/t/how-to-import-a-chart-into-my-template-without-using-cdn/89465/3

**Comment by buschhardtt** [comment]
Hallo Joe,

thank you. I think we can close this, because the topic is to difficult (not to set the script-Tags of course) for me,because I dont see any result (or errors). Maybe one day, someone find a cool solution to add this to dashboard as a widget.
I the meantime I use ethercalc in a IFrame ;-).
Bye Thomas
