### ISSUE TITLE
Issue with Chart Node

### ISSUE THREAD

**Issue by j0sh162** [FlowFuse/node-red-dashboard#1210]
### Current Behavior

When working with the chart node and using a bar type and you have more than 9 items it ends up creating the new bars with a very transparent and lightly coloured bar instead of repeating the colours as you can see here.
![image](https://github.com/user-attachments/assets/bf3534eb-3074-40c2-a57b-4d7103c531d6)

### Expected Behavior

I expected the node to reuse the colours which had already been used similar to the pie chart.

### Steps To Reproduce

You can reproduce this by dynamically inserting more than 9 items into the chart node.

### Environment

- FlowFuse version: 2.7.0
- Node.js version: 18.20.4
- npm version: 
- Platform/OS: 
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by hardillb** [comment]
I've moved this to the Dashboard repo

**Comment by joepavitt** [comment]
Any updates on this @gayanSandamal?

**Comment by gayanSandamal** [comment]
> Any updates on this @gayanSandamal?

It's almost completed but I didn't create the PR because I need to do more manual testings on this.
I will create the PR and keep it as a draft until finish with the testings

<img width="1703" alt="Screenshot 2024-08-20 at 23 33 14" src="https://github.com/user-attachments/assets/701a96f6-e9e4-4759-85c7-bf64868e5aaf">
