### ISSUE TITLE
Hover to show all topics in x property value when hovering

### ISSUE THREAD

**Issue by E1cid** [FlowFuse/node-red-dashboard#1254]
### Description

With multi line chart if x property has multiple y values when you hover only one is shown, this differs to dashboard one behaviour. 
Would be nice to see all y topics  with the same x property value
![Screenshot_20240901-101351](https://github.com/user-attachments/assets/9714454e-69b9-4e63-a99b-42bc5ccec5e7)

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Have found the ChartJS setting for this: https://www.chartjs.org/docs/latest/samples/tooltip/interactions.html

But it doesn't compare by `x` value, it compares by `index` in the dataset, so if the data is in a different order, it's not matching up correctly.

Haven't spent more than 10 mins on this, but want ed to report it here as it's a feature we should support sooner rather than later.
