### ISSUE TITLE
ui-table - Data is Always Replaced, Even if "Action" is "Append"

### ISSUE THREAD

**Issue by jtempletmg** [FlowFuse/node-red-dashboard#1407]
### Current Behavior

Using ui-table on a dashboard, if the "Action" is set to "Append", the data in the table is always cleared.

### Expected Behavior

Using "Action" "Append" should add any incoming data sets to the table.

### Steps To Reproduce

1. Add ui-table to a dashboard
2. Set the "Action" to "Append"
3. Trigger multiple data sets to the widget
4. Only the last data set is visible

Note that this behavior persists until you toggle the "Action" to "Replace" then back to "Append". When the dashboard is deployed after toggling the "Action" the "Append" starts working.

### Environment

- Dashboard version: 1,18.1
- Node-RED version: 4.0.5
- Node.js version: 18.20.4
- npm version: 10.7.0
- Platform/OS: Raspbian Bullseye
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by jtempletmg** [comment]
Additional comment on this: user on Discord noted that if the Action was toggled to "Replace" then back to "Append" and the deployed it does indeed start appending.

**Comment by gayanSandamal** [comment]
@joepavitt I did couple of testings on my local instance but I couldn't recreate it

https://github.com/user-attachments/assets/24531451-eb61-4391-ab8b-6c1fd012f93c

But when I did the same on the dashboard demos instance I could recreate the scenario https://dashboard-demos-dev.flowfuse.cloud/dashboard/table-1

Assuming the root cause is with setting the default in ui_table.js I've created a PR with the fix but in DRAFT mode

https://github.com/FlowFuse/node-red-dashboard/pull/1408
