### ISSUE TITLE
Title remains empty when 'Show Page Name in Header' option is off and header option style is fixed

### ISSUE THREAD

**Issue by MaWa53** [FlowFuse/node-red-dashboard#1545]
### Current Behavior

In Dashboard 1.0 you could set a Title text of the Dashboard on the Site Tab.
In 2.0 you can set a name in the settings, which never appears. 

If you set 'Show Page Name in Header' option and use the default Header Options Style 'Default' the page name is shown but the header remains empty if the option is off.
If you use a fixed sidebar you either show redundant page names in the side bar and the header or nothing.

### Expected Behavior

Ability to decide to show Dashboard name when 'Show Page Name in Header option' is off.
If you decide to use 'Header Options' style Fixed and disable 'Show Page Name in Header' option  AND you set a Dashboard name then that name should appear in the header.

### Steps To Reproduce

Turn off the 'Show Page Name in Header' option and set Header Options style to Default or fixed.

### Environment

- Dashboard version: 1.20.0
- Node-RED version: 4.0.5
- Node.js version:
- npm version:
- Platform/OS: raspberry pi bookworm
- Browser: FireFox

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by bartbutenaers** [comment]
@MaWa53,

To be honest I have not really used those settings myself.  So perhaps my proposal below is not entirely usable.  But let's give it a try...

So currently you have an option to show the page name in the header or not:

![image](https://github.com/user-attachments/assets/4b8d49ee-3bf1-4a57-8385-8be27e8d80ed)

When the page name is not displayed, you want to see the dashboard name (instead of an empty header).  From your description I 'understand' that the dashboard should determine - based on all a series of settings - whether the page name or dashboard name should be displayed in the header.  Is that correct?

But wouldn't it be more flexible if the user could tell the dashboard which content needs to be displayed inside the header.  For example by replacing the checkbox by a dropdown, like in the following mockup:

![image](https://github.com/user-attachments/assets/09582515-822c-4c55-97dc-ee650c49ec32)

Remark for myself: if the dropdown would be sufficient to solve this issue, some migration logic should be added for existing nodes (which currently contain the checkbox option).

Bart

**Comment by bartbutenaers** [comment]
@joepavitt,
I don't quite understand where the `pageTitle` (see [here](https://github.com/FlowFuse/node-red-dashboard/blob/abf313079da5ecd16e6698f6c782ab3da75845af/ui/src/layouts/Baseline.vue#L111C9-L111C18)) property value is being set?  I don't see it anywhere...
Thanks for illuminating me!

**Comment by joepavitt** [comment]
> But wouldn't it be more flexible if the user could tell the dashboard which content needs to be displayed inside the header. 

Love this. Much clearer, and fixes the UX confusion experienced here.

For `pageTitle`, I'm away from keyboard today, so wouldn't be able to give you a concrete answer unfortunately. @Steve-Mcl may be able to advise

**Comment by MaWa53** [comment]
@bartbutenaers

your proposal is certainly better than mine. 

You can set a dashboard name (for what ever purpose it exists today) and decide whether to show it as title in the header (if you use a header) or not. 

It is very improbable that the page name remains empty because of its use in the sidebar, so you don't need any automatism if you use the page name option.  Although IMHO I would enforce page names.

Well, finally you may think of a fourth option: Dashboard name + page name . This could be usefull if you use an iconized sidebar. 

You can thereby always recognize what dashboard and what page is currently displayed. 

I e.g. use several raspi based sensors in my house for temperature, humidity, air pressure and CO2 plus air quality (organic vapors).
So I can load one or more dashboards for easy comparison of values and their history graphs.

**Comment by joepavitt** [comment]
> It is very improbable that the page name remains empty because of its use in the sidebar, so you don't need any automatism if you use the page name option. Although IMHO I would enforce page names.

We have many users that don't want to show the page names, and often it's to replace it with custom content, which you can do with a Template Node, e.g. placing company logos there for branding purposes.

**Comment by joepavitt** [comment]
> You can set a dashboard name (for what ever purpose it exists today)

This is used as the Application name when you install your Dashboard as an app on iOS/Android.

**Comment by MaWa53** [comment]
@joepavitt 

> This is used as the Application name when you install your Dashboard as an app on iOS/Android.

Thank you for the clarification.
