### ISSUE TITLE
Button widget: Option missing - 'If msg arrives on input, emulate a button click'

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#209]
As with D1, the Button widget should have an option to emulate a button click if a message is passed in.  It should then send the received message, but with the configured topic and payload.
However, if the message includes msg.enabled then this should not emulate a click.

**Comment by i8beef** [comment]
Agree about the button pass through option. I use it the exact same way as @colinl in my UI in several places.

**Comment by colinl** [comment]
> I use it the exact same way as @colinl

In fact I don't use the feature, the problem I was having was that the message was always emulating a button click, even for enable/disable messages.  I see that this has now been fixed and enable/disable messages do not get passed through.  I expect @joepavitt would be grateful to hear your use case

**Comment by i8beef** [comment]
My case is used to disable the button according to input, as you indicated, sorry for the confusion.

I was looking for any open bugs around "pass through not supported" across the suite of controls and wanted to add it here. If I understand the fix here, does it not pass through ANY messages EVER now, or is it doing some filtering to ONLY not pass through the disable / visibility stuff? I would really prefer an explicit "do not passthrough" on every control for consistency at least, but also so I can be sure I'm in control of that behavior instead of relying on convention.

**Comment by i8beef** [comment]
That works for me too, though I liked the consistency of the old dashboard having this checkbox on each control instead of only select ones... but Im happy with the current state then for my own needs. Just being an advocate for the experience for others now 😄
