### ISSUE TITLE
Trigger HTTP request on navigation to page

### ISSUE THREAD

**Issue by RyIot3329** [FlowFuse/node-red-dashboard#217]
How do you trigger an http request when someone navigates to a certain page?

**Comment by joepavitt** [comment]
Hi @RyIot3329 - currently we don't have any nodes that trigger on arrival on a page, but this is a great idea for a new feature. I'll update the issue accordingly.

**Comment by colinl** [comment]
The current dashboard ui control node features should be considered when designing the equivalent for Dashboard 2

**Comment by RyIot3329** [comment]
With it being built ontop of Vue3, could one use the onMounted() lifecycle hook to trigger a payload to an httprequest node?

**Comment by joepavitt** [comment]
Yes, but will want to think slightly bigger here. W

We use SocketIO to communicate between UI and Node-RED, so, `onMounted()` we could send some kind of ui-event (need to come up with an appropriate schema that would support other ui event mechanisms).

We then need a node in Node-RED that can listen to these events and then `send(msg)`  inside Node-RED so that you can connect it to _anything_ (in your case here, a HTTP Request node)

**Comment by RyIot3329** [comment]
Ah yes that makes a lot of sense and sounds like a great feature. the onMounted() hook is what brought this question up. Thank you!

**Comment by joepavitt** [comment]
Just circling back to some old issues - this has been possible for a while now by using the `ui-event` node - see [docs](https://dashboard.flowfuse.com/nodes/widgets/ui-event.html#event-ui-event)

You can wire the output of the `ui-event` to a `http` node and conduct a server-side HTTP request
