### ISSUE TITLE
Last notification is send again when refreshing the page

### ISSUE THREAD

**Issue by Mika97400** [FlowFuse/node-red-dashboard#219]
When refreshing dashboard page, the last notification is opening again. You can refresh the page multiple times and the notification is send again and again.

**Comment by joepavitt** [comment]
Thanks for flagging! Think I know the cause, will get it addressed, although I'm locked into some other work atm.

May be end of this week, latest next week

**Comment by joepavitt** [comment]
Just updating here, have investigated and this requires some (justified) architectural changes to better support this. Currently, when the Dashboard is loaded, we run the `onInput` functionality for all widgets in order to load existing state, however, this for something like the notification causes the notification to show again.

We should look at separate `onInput` from `loadState` functions across all of our widgets, but support (where in most cases this is is appropriate) shared logic.
