### ISSUE TITLE
Widget: Audio

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#52]
### Description

Description from Dashboard 1.0:

<img width="549" alt="Screenshot 2023-06-23 at 22 10 45" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/99246719/d44264ca-11a8-4852-babb-fd8b74a4213a">

### Properties

Properties from Dashboard 1.0: 

<img width="512" alt="Screenshot 2023-06-23 at 22 10 33" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/99246719/16c1d648-2c40-4bc2-8ddf-d69977d05147">r

### Events

Not sure we need any events, this node would likely have 0 outputs.

### Controls

- **enabled**: this widget can be enabled/disabled

### Existing Examples

Existing Dashboard 1.0

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by chrismahoney** [comment]
I am most likely going to need this after having stumbled upon the 2.0 package in the palette manager, if I do and make headway I'll update here.

**Comment by haichenzhu** [comment]
looking forward to having this feature available on dashboard 2.0

**Comment by bartbutenaers** [comment]
The ui-template solution from @Steve-Mcl (see [this](https://discourse.nodered.org/t/play-simple-audio-with-ui-template-dashboard-2/92943/5?u=bartbutenaers) discussion on Discourse) is a useful temporary workaround, and might be a good starting point for a core ui node.

**Comment by bartbutenaers** [comment]
@joepavitt 
If you want you can also assign this one to me.  Will have a look at it as soon as I find time.

**Comment by bartbutenaers** [comment]
> It would be useful to have output events

@Steve-Mcl,
+ I thought that there would be something like a single (invisible) audio player, bound to the ui (similar to the ui-notification node).  Because it seems to make sense to me that you only listen to a single audio source.  
+ Or do you mean that you can add an audio player to every group (similar to e.g. a ui-button), and that it can be visible or not:
   ![image](https://github.com/user-attachments/assets/b9ca6bd8-aa98-479f-a8a1-ff160cdf8893)
   And that both the user actions and the audio state changes will be send as output messages.

**Comment by Steve-Mcl** [comment]
Either way Bart. I am just stating knowledge is power 😇

**Comment by bartbutenaers** [comment]
Thanks Steve for that lousy advise 😂

I created a draft implementation last night for the first option.  It works but it offers very few flexibility.  So I will change it to option 2...

**Comment by bartbutenaers** [comment]
@Steve-Mcl (an others of course...)
Making progress but now doubting a bit:
1. I assume the *"value"* of this widget is the src, so that should be applied via the `msg.payload` (instead of via `msg.ui_update.src`.  Is that correct?
2. I need to be able to start/pause/stop the audio via input messages.  Do I need to do that via `msg.ui_update.state` or some other way perhaps?

**Comment by kd9lsv** [comment]
Curious if it was the intention in the migration to get rid of the ability to use TTS in the audio node?

**Comment by bartbutenaers** [comment]
@kd9lsv,
No not on purpose.  The audio widget was already an long time, so I created one with the basic functionality.

But yes indeed that might be a useful addition.

Can you create a new issue (feature request) to add it again, to avoid it will be forgotten.  Thanks!
Bart
