### ISSUE TITLE
Groups Order when editing widget

### ISSUE THREAD

**Issue by arturv2000** [FlowFuse/node-red-dashboard#660]
### Description

I looked in the GitHub issues and don't seem to have found this, if it exists.. sorry...

When editing a widget, and choosing the group where to place the widget, would be nice that the group order was first `page` then `group`. I think it facilitates the selection specially when there are a lot of groups, and some pages may have groups with similar names. And it was the default behaviour of Dashboard 1.

As it at the moment, DashBoard 2
![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/503f681a-09f9-46f2-9d00-e3ca22e45182)

As it is in Dashboard 1
![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/3bff67ba-57e0-454b-b785-e4f8da3ce356)

The page order could be as in Dashboard1 by the order in layout, or by alphabetical order, either option seems fine as long is grouped by the `page`.

Thank You

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Great suggestion - will add to the list!

**Comment by joepavitt** [comment]
@Steve-Mcl I just want to implement this, thinking it was going to be easy, then realised this is all under the covers in Node-RED because it's a config node selector. Fairly sure I've got no control over this ordering, without changing the names/labels of the groups to be `<Page Name> - <Group Name>`?
