### ISSUE TITLE
UI Gauge - Improve icon sizing at varying sizes

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#888]
### Current Behavior

https://discourse.nodered.org/t/gauge-icon-text-sizing/88176

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
@Paul-Reed just to drop some thoughts here as I'm experimenting with this locally atm - it's _complicated_ to get right.

We can't depend on the config's width/height here as a size of `3` could be very different depending on the screen size, so, we need to consider physical size. I was then thinking of bucketing the physical size into `xs`, `sm`, `md`, `lg`, `xl` which I think could work, but I then need variations for each gauge type, and also need to account for the fact that the dial width can be customised by the user too.

As such, I think we need a monitor of the physical gauge size, which I'll proceed with, and update accordingly.

**Comment by Paul-Reed** [comment]
Thanks @joepavitt - I think most node-RED users are familiar with fontawsome, who also bucket the physical sizes, so yes, sounds good.
The default starting point for FA is 16px, and work up or down from there - 

![fontawsome](https://github.com/FlowFuse/node-red-dashboard/assets/973580/21af1f16-f866-4c69-b264-97b646da351a)

I think I commented previously that I had hoped that we would have had a choice of either text OR an icon, instead of both, which would may of given us more breathing space with the sizing.

**Comment by joepavitt** [comment]
> I think I commented previously that I had hoped that we would have had a choice of either text OR an icon, instead of both, which would may of given us more breathing space with the sizing

In the PR I've opened, I now handle "icon only" as a separate use case, and increase the icon size a little in that case.
